### PR TITLE
Making it modular with express routes

### PR DESCRIPTION
**Pull request by nicola**
Should I make this working for liveUpdates instead?

### CODE REVIEW

**Comment by nicola** [comment]
This is explained in #9

**Comment by timbl** [comment]
I'm afrad I have just been workig in liveUpdates and there may be bits which the master branch does not have and should have.  Like I just put the proxy into liveUpdates.  We should merge liveUpdates back onto the main branch I think

**Comment by nicola** [comment]
Ok, we then wait for liveUpdate to be merged for this merge

**Comment by timbl** [comment]
Ok I have merged liveUpdate into master, do go ahead make it router-happy now

**Comment by nicola** [comment]
So I have been implementing it and it worked apart from the new websocket.

I haven't had time until now (I have now substantially less workload at uni), but I have concern with our usage of the library `express-ws`, I have not clear whether our websocket server **must** be the same or if it can be on a different machine or on a different port.

So, assuming we want to achieve the best flexibility, I submitted an issue to the maintainer of express-ws, that might help, in there I suggest three options that differ from the one that I suggest in this PR.

https://github.com/HenningM/express-ws/issues/8

**Comment by nicola** [comment]
working on a new version

**Pull request closed without merging**
