### PR TITLE
Fix delete on containers

### PR DESCRIPTION
**Pull request by deiu**
Previously, the delete operation did not remove the corresponding meta and acl files. It also failed when trying to delete an empty container.

### CODE REVIEW

**Comment by deiu** [comment]
Ready for merge.

**Comment by sandhawke** [comment]
Considering opening an issue on whether ACLs should survive delete.   It's unclear.   There are use cases on either side of that.    On w3.org they do.

**Comment by deiu** [comment]
This is the ACL document which lives within the container. If the container is deleted, it would be impossible to keep the ACL document.

**Comment by dmitrizagidulin** [comment]
Fixing tests, stand by

**Comment by dmitrizagidulin** [comment]
:+

**Pull request merged**
