### PR TITLE
Fixes #213

### LINKED ISSUE #213: Bug in index.html handler
When requesting `/foo/index.html`, ldnode should not concatenate `index.html` to the requested patch by default:

```
GET /foo/index.html
```

```
404 Not Found - /foo/index.html/index.html
```

### PR DESCRIPTION
**Pull request by deiu**
Do not append `index.html` by default to the requested path.

### CODE REVIEW

**Comment by deiu** [comment]
Ready for merge.

**Comment by dmitrizagidulin** [comment]
Getting some test failures. Investigating.

```
  1) Identity Provider generating a certificate should generate a certificate if spkac is valid:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
  2) Identity Provider generating a certificate should not generate a certificate if spkac is not valid:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
  3) Identity Provider creating an account with POST should not create a WebID if it already exists:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by deiu** [comment]
Could it be your local cache or some old files? It passes all tests just fine here and on Travis.

**Comment by dmitrizagidulin** [comment]
What the devil. I cloned a fresh repo, checked out this branch again, and this time the tests passed. 
Ah well, sorry for the confusion. :+1: from me.

**Pull request merged**
