### PR TITLE
Fix cli params (-idp, -sA, -sM, -fU)

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Fixes issue #283.

### CODE REVIEW

**Comment by nicola** [comment]
should we go with this instead -> https://github.com/linkeddata/ldnode/pull/256 ?
The one I am linking re-orders and removes abbraviations

**Comment by dmitrizagidulin** [comment]
Sure, that one works too!

**Comment by nicola** [comment]
let's merge it then!

**Comment by nicola** [comment]
Will merge   #256

**Pull request closed without merging**
