### PR TITLE
Fixing issues with proxy headers

### LINKED ISSUE #253: Proxy dropping 'Location:' header
Proxy is not returning the `Location:` header from original server. This is especially important when following `301 Moved Permanently` redirects.

For example, requesting directly:

```
curl -v http://www4.wiwiss.fu-berlin.de/bookmashup/persons/Tim+Berners-Lee
< HTTP/1.1 301 Moved Permanently
< Location: http://wifo5-03.informatik.uni-mannheim.de/bookmashup/persons/Tim+Berners-Lee
```

Through proxy:

```
curl -vk https://localhost:8443/proxy?uri=http%3A%2F%2Fwww4.wiwiss.fu-berlin.de%2Fbookmashup%2Fpersons%2FTim%2BBerners-Lee

< HTTP/1.1 301 Moved Permanently
< X-Powered-By: Express
< Vary: Origin
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: User, Location, Link, Vary, Last-Modified, Content-Length
< Date: Wed, 17 Feb 2016 20:13:13 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
<
```

Note that `Location` is in the Expose-Headers, correctly, but not actually being returned.

### PR DESCRIPTION
**Pull request by nicola**
- fixes #253, #252, #251, #250 issues with proxy
- Add a simple test

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Looks good so far, but I think it's still not proxying the `Accept:` header in the *request* (it passes along the response headers correctly)

**Comment by dmitrizagidulin** [comment]
NICE! Removing the `connection:` header fixed my proxy issue (it was passing `Accept:` correctly).

(I wonder why those CI tests failed.. they're passing for me locally)

**Comment by nicola** [comment]
They pass on my machine

**Comment by dmitrizagidulin** [comment]
Force a push again, have CI re-run the tests?

**Comment by dmitrizagidulin** [comment]
Bumped Travis's node_js directive to 4.0 and 5.0, as discussed on gitter.

**Comment by nicola** [comment]
Tests still break, unfortunately I don't have time to look at this now, but it must be some slightly hidden trivial fix.

**Comment by nicola** [comment]
A clean install of ldnode actually does fail the test on my machine

**Comment by dmitrizagidulin** [comment]
@nicola - what OS?

**Comment by nicola** [comment]
@dmitrizagidulin Mac OS X, some of our dependencies must have updated their version (I guess `nock` does not serve the status code)

**Comment by nicola** [comment]
In fact, `nock` was not serving the status code, should be fixed in latest

**Comment by dmitrizagidulin** [comment]
Good good, now one of the builds succeeds :)  (How do we get the other one to pass?)

**Comment by nicola** [comment]
I had to re-run one since travis some times loses connection when fetching databox for the webid used in ACL

**Comment by dmitrizagidulin** [comment]
You rock :)

**Pull request merged**
