### PR TITLE
Removing uriBase/uri

### PR DESCRIPTION
**Pull request by nicola**
Now the uriBase is set by the incoming request.

To load ldp on `http://nicola.io/LDP` and map it to /home/nicola, run

```
ldnode --mount /LDP --base /home/nicola
```

To load ldp on `http://nicola.io/` and your current working dir is `/home/nicola`, run 

```
ldnode
```

:)

### CODE REVIEW

**Comment by martinmr** [comment]
Does this cover every appearance of uriBase?

**Comment by nicola** [comment]
yes absolutely, it fixes https://github.com/linkeddata/ldnode/issues/47

**Comment by deiu** [comment]
The changes seem reasonable. Quick question though: why is this function still here: https://github.com/nicola/ldnode/blob/no_uriBase/container.js#L21?

**Comment by martinmr** [comment]
I think the only issue that should be fixed before merging is the last one. I plan to remove the root container issue (along with all the other issues involving containers and the meta file) tomorrow and it's an entirely separate issue.

**Comment by nicola** [comment]
overall comment: @deiu your changes were not rolled back and this is a PR for baseUri not for other issues:

1. that function is just a function that creates the root container. the `baseUri` mentioned in there is just the name of the variable, nothing to do with the `options.baseUri`. It is only used in by @martinmr in https://github.com/nicola/ldnode/blob/no_uriBase/index.js#L51
2. That exact acl suffix has not been mentioned in your earlier PR (we only touched here https://github.com/linkeddata/ldnode/commit/cfbc744f6b2e266837dc2608d832a1c9842db6aa), so I guess we both skipped it! This should be a different issue I just created let's discuss this elsewhere #59 #60
3. This should be discussed in #60 and in a different PR
4. No changes have been rolled back

**Pull request merged**
